In [38]:
import pandas as pd
pd.set_option('display.max_rows', 10)

# Datensatz einlesen
df = pd.read_csv('/Users/tianxinangelama/Documents/Studium/4. FS/DMS/DMS_data/GFP_AEQVI_Sarkisyan_2016.csv')

# split into multiple columns, 1 column for every mutation
df_ind_col = df

df_ind_col[['m1', 'm2', 'm3', 'm4', 'm5', 'm6', 'm7', 'm8', 'm9', 'm10', 'm11', 'm12', 'm13', 'm14', 'm15']] = \
    df_ind_col['mutant'].str.split(':', 14, expand=True)

# reduce df to fscore, m1 - m15
df_only_fscore_mutations = df_ind_col

df_only_fscore_mutations = df_only_fscore_mutations.drop(['mutant', 'mutated_sequence', 'DMS_score_bin'], axis=1)

df_only_fscore_mutations.head()

/var/folders/tn/1strgsg5455dq9n93kfzv8kh0000gn/T/ipykernel_22017/738230302.py:11: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  df_ind_col['mutant'].str.split(':', 14, expand=True)

,DMS_score,m1,m2,m3,m4,m5,m6,m7,m8,m9,m10,m11,m12,m13,m14,m15
0,1.301030,K3R,V55A,Q94R,A110T,D117G,M153K,D216A,None,None,None,None,None,None,None,None
1,3.137350,K3Q,V16A,I167T,L195Q,None,None,None,None,None,None,None,None,None,None,None
2,1.553913,K3Q,Y143C,N164D,S205P,A227T,None,None,None,None,None,None,None,None,None,None
3,3.404237,K3Q,Y143N,V193A,None,None,None,None,None,None,None,None,None,None,None,None
4,3.738586,K3R,None,None,None,None,None,None,None,None,None,None,None,None,None,None

In [39]:
# df mutants with 1x mutation
# copy df
df_1_mutation = df_only_fscore_mutations.copy()

# remain rows with empty values in m2
df_1_mutation = df_1_mutation[df_1_mutation['m2'].isna()]

print(df_1_mutation)

       DMS_score     m1    m2    m3    m4    m5    m6    m7    m8    m9   m10  \
4       3.738586    K3R  None  None  None  None  None  None  None  None  None
48      3.750487    K3Q  None  None  None  None  None  None  None  None  None
703     3.666278    K3E  None  None  None  None  None  None  None  None  None
924     3.698336    K3M  None  None  None  None  None  None  None  None  None
1160    3.629775    K3T  None  None  None  None  None  None  None  None  None
...          ...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
51709   3.809468  Y237N  None  None  None  None  None  None  None  None  None
51710   3.760217  Y237C  None  None  None  None  None  None  None  None  None
51711   3.754101  Y237D  None  None  None  None  None  None  None  None  None
51712   3.673173  Y237F  None  None  None  None  None  None  None  None  None
51713   3.735417  Y237H  None  None  None  None  None  None  None  None  None

        m11   m12   m13   m14   m15
4      None  None  None  None  None
48     None  None  None  None  None
703    None  None  None  None  None
924    None  None  None  None  None
1160   None  None  None  None  None
...     ...   ...   ...   ...   ...
51709  None  None  None  None  None
51710  None  None  None  None  None
51711  None  None  None  None  None
51712  None  None  None  None  None
51713  None  None  None  None  None

[1084 rows x 16 columns]

In [40]:
# list possible mutations in mutants with 1x mutation
# create list with values of m1
possible_mut_1x_mut = df_1_mutation['m1'].tolist()

# delete duplicates
possible_mut_1x_mut = list(set(possible_mut_1x_mut))

print(possible_mut_1x_mut)

['T118K', 'N170T', 'D133A', 'P211A', 'H81P', 'S86A', 'K107G', 'D82V', 'D76E', 'H148Q', 'L125R', 'E6G', 'V61M', 'S205F', 'T59A', 'K156R', 'I167N', 'D102G', 'V68L', 'L7Q', 'F71S', 'K26Q', 'G67C', 'K85T', 'V55G', 'F27S', 'D133H', 'D173A', 'V193L', 'Y39C', 'K209I', 'K107M', 'E34A', 'G35S', 'D155E', 'V224L', 'K41E', 'P89H', 'H169Y', 'A227S', 'S175T', 'G191V', 'D190G', 'M218V', 'I14F', 'Y143N', 'V224A', 'V55A', 'K3E', 'F99S', 'E32V', 'G174D', 'E172K', 'P211H', 'H231P', 'F99Y', 'M88V', 'I14L', 'Y145H', 'R122H', 'L64V', 'G134S', 'D234H', 'V55M', 'K52N', 'I161T', 'M153V', 'N135Y', 'Y145C', 'N198T', 'E222G', 'Q94R', 'G127C', 'F165V', 'K214T', 'F8V', 'K156M', 'Y151H', 'D155A', 'G138V', 'N146Y', 'H77P', 'D19G', 'L207R', 'N212K', 'H199L', 'P58S', 'S147R', 'F165H', 'D36A', 'K126E', 'H139R', 'L220Q', 'N146K', 'Q69R', 'K79Q', 'K113M', 'H148N', 'P58A', 'N198S', 'M88I', 'V219I', 'R109P', 'G138E', 'G232V', 'I98V', 'F71C', 'M153R', 'E5D', 'S202N', 'V219D', 'S30P', 'M88R', 'F114S', 'K79R', 'V29M', 'Q80H', 'G4A', 'D216N', 'F100C', 'E5G', 'A37G', 'V176L', 'Q183R', 'D173V', 'L15P', 'G33R', 'E95D', 'I188A', 'K52Q', 'S65L', 'T43A', 'K166T', 'E172G', 'I229V', 'T38N', 'N146T', 'H217N', 'V22L', 'C48R', 'V93L', 'T63S', 'M88K', 'Y106N', 'I128A', 'K166M', 'T118I', 'Y151F', 'V176M', 'L15V', 'A226S', 'L178H', 'L7P', 'K158E', 'N146S', 'C70Y', 'L195P', 'E235G', 'A87G', 'Q69H', 'L42R', 'L42M', 'N170K', 'E115A', 'T203S', 'P54T', 'H81R', 'F8H', 'N170Y', 'A227P', 'I188N', 'P13R', 'D36Y', 'L141P', 'N170S', 'D216G', 'H231L', 'N144S', 'C70R', 'I47F', 'K85R', 'V193A', 'I167L', 'S208C', 'M153I', 'N23I', 'E142V', 'V29E', 'L201H', 'L64M', 'T59I', 'K41T', 'K162T', 'N164G', 'D180V', 'F71I', 'G174C', 'P192H', 'M153L', 'H77C', 'D117V', 'F84L', 'Y200D', 'S147C', 'T59P', 'T38I', 'E5K', 'P58L', 'P211S', 'N144T', 'K101Q', 'N135I', 'F46L', 'E124K', 'D36V', 'L221V', 'Y92N', 'K140V', 'E132A', 'D180G', 'G228E', 'R73H', 'V11L', 'L178F', 'L207M', 'E34V', 'V163M', 'E5V', 'D210G', 'D129G', 'D173G', 'K26N', 'K209T', 'Y145D', 'E213V', 'D173H', 'D19E', 'K26T', 'N185S', 'K41R', 'D210V', 'D197A', 'S175R', 'H77R', 'Y151D', 'D129V', 'E17V', 'T97A', 'I14T', 'Y143C', 'V93A', 'N23D', 'S72R', 'L178I', 'S65P', 'S86Y', 'H217P', 'N105K', 'H231Q', 'T186S', 'H169L', 'N185T', 'I171V', 'K52R', 'K214M', 'D190V', 'K26E', 'L178V', 'K162Q', 'L125Q', 'V176A', 'G189D', 'K26G', 'I171L', 'K52G', 'V163G', 'Q94L', 'K162E', 'T230I', 'G67S', 'E34K', 'Y151C', 'F130Y', 'G31V', 'R73L', 'L195V', 'D19A', 'F46Y', 'V22G', 'T38S', 'N198K', 'H199R', 'L53M', 'Q80L', 'E17A', 'Q94P', 'T43I', 'Q204R', 'G91A', 'K3M', 'K41N', 'G40S', 'F83Y', 'I188T', 'S72I', 'V93F', 'D155V', 'S202T', 'K162R', 'I229D', 'P196A', 'G232S', 'F8C', 'N164D', 'G116C', 'N159S', 'E17G', 'N146D', 'A227T', 'G174S', 'K101M', 'D102N', 'L221R', 'D180E', 'F71Y', 'T43N', 'Y182S', 'D180Y', 'P75T', 'T63A', 'F83S', 'F114Y', 'L64P', 'G4S', 'V193E', 'F165I', 'N170G', 'L236M', 'D197Y', 'K126R', 'P75H', 'K3T', 'N135S', 'K156E', 'A227D', 'D133Y', 'L236Q', 'G232R', 'E32G', 'D36G', 'N23S', 'H217R', 'L15Q', 'K52M', 'H148Y', 'Y143D', 'M233A', 'N121S', 'D197V', 'F100L', 'R109H', 'P196L', 'E115K', 'P75S', 'Y66C', 'S202I', 'G104A', 'V12L', 'R73C', 'N159Y', 'F165Y', 'H148L', 'Y66N', 'P196S', 'L44R', 'K3Q', 'E142G', 'I229T', 'N185I', 'N23T', 'D36K', 'G4D', 'Y200F', 'G35C', 'G191C', 'T203P', 'P13A', 'V61L', 'P13H', 'V93D', 'S208G', 'Y237D', 'M78K', 'Q80R', 'V219A', 'Q183L', 'D76G', 'T38A', 'Y182C', 'G228R', 'G67V', 'N149H', 'K162N', 'P211T', 'K101N', 'E124G', 'S175C', 'K131R', 'S175N', 'G24A', 'E172V', 'Y74C', 'S175G', 'R215C', 'S147N', 'F27I', 'K79T', 'H81L', 'Y92F', 'M153T', 'N121I', 'H148R', 'K166N', 'Q184R', 'S72N', 'E142K', 'D129A', 'Y151N', 'Y143F', 'V112E', 'S72C', 'F8Y', 'V112A', 'G24C', 'K131Q', 'H169P', 'D190A', 'A206S', 'G116D', 'I188L', 'I229F', 'N149T', 'N159K', 'N159I', 'F27V', 'R168S', 'V11A', 'L18R', 'G91S', 'D180H', 'T9A', 'V224G', 'H199P', 'M88T', 'S202G', 'R215L', 'P54L', 'G127S', 'H25R', 'N135H', 'Y39D', 'S30Y', 'A37S', 'K107R', 'K162M', 'D133V', 'L207Q', 'E132K', 'H217D', 'F8I', 'F130L', 'E32D', 'T50I', 'A87T', 'N121H', 'H181N', 'I98F', 'Y145N', 'K113E', 'A37V', 'D76A', 'D133E', 'E142A', 'F130V', 'L18P', 'S28R', 'K158Q', 'P187T', 'V61A', 'N185D', 'V12A', 'H181R', 'P187L', 'L201R', 'S30T', 'N164S', 'K113G', 'T203I', 'G10E', 'S72G', 'I136M', 'S208R', 'K131M', 'D36H', 'L137M', 'G33S', 'E32K', 'T9P', 'Y200N', 'L53P', 'R168C', 'D82N', 'Y237H', 'D102Y', 'K209S', 'D129Y', 'H139L', 'N159D', 'L44P', 'A206D', 'V22E', 'V22A', 'E213G', 'Y151S', 'L15R', 'I167S', 'A206V', 'S65T', 'G33D', 'A154T', 'N23H', 'L195Q', 'T225S', 'N198I', 'E90A', 'L195R', 'V150A', 'D19N', 'M233K', 'F223L', 'N23K', 'N144I', 'I123A', 'E34G', 'K107T', 'G134C', 'E6R', 'K140M', 'K158N', 'M78T', 'Y200H', 'N105I', 'K107E', 'Y39N', 'A226D', 'A206T', 'N159H', 'Y92H', 'N121D', 'D76V', 'N135D', 'M218K', 'G51D', 'F71L', 'M233R', 'R122L', 'E132G', 'T97N', 'H77N', 'V29A', 'G10V', 'S28I', 'T203A', 'G138A', 'P54A', 'H231R', 'V68E', 'K52E', 'I161V', 'E235D', 'N149Y', 'Q94H', 'I98L', 'G189S', 'A154V', 'Q204L', 'L42Q', 'G51S', 'L18Q', 'L137Q', 'F84C', 'F100S', 'F165C', 'Y74F', 'F27L', 'I47N', 'D117A', 'E5R', 'K79M', 'E222A', 'K41M', 'E235A', 'N212S', 'F165S', 'I152V', 'L194Q', 'I167F', 'T43S', 'H181Q', 'I136T', 'F8L', 'R96P', 'D103G', 'H139Y', 'D173N', 'L236R', 'N212T', 'K85E', 'K107A', 'T49I', 'K156Q', 'S28N', 'A87P', 'D197G', 'T63P', 'E132V', 'E95G', 'N198Y', 'D216E', 'M218I', 'Q157P', 'F46V', 'A87S', 'N105D', 'T50S', 'F46S', 'I123T', 'Y66F', 'K113Q', 'N212Y', 'H181L', 'E6V', 'P89S', 'T118A', 'D21V', 'S86P', 'T50A', 'F83I', 'D180N', 'L42P', 'F223V', 'H81D', 'L125P', 'N121Y', 'D19V', 'E111Q', 'D102H', 'N135T', 'H77L', 'R168L', 'K209E', 'R215S', 'G228V', 'D234V', 'Y145F', 'Q69P', 'K45M', 'S30A', 'E95Q', 'E115G', 'S30F', 'L178P', 'V16F', 'G191A', 'C70G', 'T38P', 'V11M', 'G160V', 'G24S', 'S28C', 'N170I', 'I128V', 'M233T', 'N105Y', 'R122S', 'K158V', 'L137R', 'I167M', 'E95A', 'Q184L', 'N170H', 'N198H', 'A226V', 'Q204H', 'I47L', 'M88A', 'P187S', 'H169R', 'H77Q', 'T97S', 'D133N', 'N121K', 'S202C', 'D21A', 'D103N', 'I98T', 'H217L', 'K140R', 'S205A', 'H148P', 'L178R', 'E124V', 'P187H', 'F46I', 'E90K', 'R96C', 'Y237N', 'I152F', 'Y106C', 'T108A', 'Y143H', 'H199Y', 'P192L', 'T43P', 'K107Q', 'S65A', 'D133G', 'L207P', 'L60I', 'D197N', 'F8S', 'T225P', 'K140E', 'A179S', 'A37P', 'F100Y', 'M233L', 'I47T', 'T230P', 'E235V', 'I152T', 'I161F', 'V11G', 'K101T', 'N144H', 'V12M', 'T9I', 'I128T', 'Y200C', 'P13S', 'Q69L', 'H77Y', 'R96H', 'D36E', 'T225A', 'A37D', 'G189A', 'F114C', 'M218R', 'T62I', 'H25Q', 'G160D', 'F99L', 'E90D', 'E6K', 'K113R', 'D129N', 'V193M', 'N212D', 'I229N', 'K166R', 'I136N', 'T9S', 'Q157R', 'L220P', 'N105S', 'T49P', 'I171T', 'K26R', 'L53R', 'R109G', 'K166Q', 'P54S', 'V176E', 'A179T', 'Y182F', 'Y143S', 'N198D', 'V61E', 'F99I', 'G232D', 'I167T', 'P58H', 'H81Q', 'D190N', 'I123F', 'K45R', 'M233V', 'T49A', 'K101R', 'I161L', 'Y182N', 'K26M', 'W57R', 'A110D', 'T230S', 'D21N', 'K41Q', 'K126N', 'D21H', 'V16I', 'S30C', 'K45T', 'I136V', 'T63N', 'N105C', 'A110S', 'I167V', 'A37T', 'K126Q', 'D36N', 'K140Q', 'T49S', 'K113T', 'E95K', 'V163A', 'L201Q', 'H81Y', 'V11K', 'G10W', 'G51R', 'G160S', 'T108S', 'G160R', 'Y92C', 'G104S', 'H181Y', 'E213D', 'M78V', 'R215H', 'D210N', 'I161S', 'G40D', 'E111V', 'G160C', 'K166E', 'G191S', 'P192S', 'L201P', 'D117G', 'E17K', 'P56S', 'I128M', 'H231Y', 'F223Y', 'T62A', 'N144Y', 'Y106F', 'S86F', 'V224E', 'D117N', 'F165L', 'V193G', 'D180A', 'T230A', 'I188F', 'A179P', 'Q177R', 'V68A', 'D76Y', 'T49N', 'K79E', 'Y145L', 'E90V', 'D155N', 'E222D', 'E235K', 'D129E', 'N164H', 'L60H', 'I128F', 'M78R', 'N164Y', 'R168G', 'I171F', 'T62P', 'A206G', 'R109C', 'N149S', 'V150G', 'F114I', 'L141Q', 'K156I', 'K209R', 'F114L', 'I229M', 'Q80P', 'D102E', 'Y237F', 'F223S', 'L60P', 'N144D', 'A110G', 'D197E', 'Y145S', 'I188V', 'G116A', 'L137P', 'F130I', 'G232C', 'P196T', 'K3R', 'L7V', 'E5A', 'E111K', 'R168H', 'S205T', 'G20D', 'T118S', 'F84Y', 'E213K', 'D103E', 'C48S', 'T186A', 'S205C', 'Y39F', 'E90G', 'D102A', 'K113N', 'I123V', 'H181P', 'I188S', 'V150I', 'D234G', 'K214N', 'L236V', 'K209N', 'D234N', 'V112L', 'A87V', 'K158M', 'A179V', 'I123L', 'V163E', 'P13L', 'P89L', 'R109S', 'I128L', 'E17D', 'Y106H', 'I161G', 'T63I', 'D102V', 'N144G', 'F223I', 'N144A', 'H231N', 'F100I', 'E115V', 'K214Q', 'G138R', 'E32A', 'A226T', 'G228W', 'Q157L', 'L44Q', 'T108I', 'G191D', 'N164T', 'T97I', 'I136F', 'N146H', 'E111G', 'V176G', 'I47V', 'K126M', 'Y237C', 'K158G', 'V11E', 'V16D', 'G10R', 'Q157H', 'Q184P', 'G138W', 'V93G', 'S28T', 'K209Q', 'V55E', 'S147G', 'N149D', 'L60R', 'L44M', 'M218T', 'F130C', 'S208N', 'A110T', 'P192T', 'D117E', 'I128S', 'Y182H', 'D19H', 'E142D', 'L7R', 'H25L', 'E111A', 'N105H', 'A227V', 'I128N', 'L236P', 'L53Q', 'F83L', 'E172A', 'V22I', 'N212I', 'K214R', 'T225N', 'N164I', 'F99V', 'C70S', 'G127D', 'I171S', 'Q177L', 'M78I', 'N146I', 'G189C', 'S202R', 'M233I', 'K45E', 'K158R', 'N185Y', 'M78L', 'F84S', 'T225I', 'Y39H', 'K52T', 'K131E', 'L195M', 'F99C', 'K101E', 'H139P', 'G232A', 'T59S', 'D234Y', 'N149I', 'D21G', 'I14V', 'P89A', 'R122C', 'G134R', 'I171N', 'S28G', 'G134D', 'S205P', 'Y200S', 'V93I', 'D76N', 'G35D', 'N159V', 'L194R', 'F46C', 'L194P', 'I47S', 'T62S', 'M153K', 'V16A', 'R73S', 'S86T', 'V68M', 'K85M', 'M88L', 'F130S', 'D155G', 'N170D', 'K131T', 'K214E', 'M218L', 'L221Q', 'E95V', 'Y39S', 'G24D', 'E124A', 'K79N', 'G67D', 'H25Y']

In [41]:
# df mutants with 2x mutations
# copy df
df_2_mutations = df_only_fscore_mutations.copy()

# delete mutants with 1x mutation
df_2_mutations = df_2_mutations.dropna(subset=['m2'])

# remain rows with empty values in m3
df_2_mutations = df_2_mutations[df_2_mutations['m3'].isna()]

print(df_2_mutations)

       DMS_score     m1     m2    m3    m4    m5    m6    m7    m8    m9  \
13      3.716293    K3R  D133A  None  None  None  None  None  None  None
41      3.833353    K3N   S30Y  None  None  None  None  None  None  None
45      3.553744    K3N  V150A  None  None  None  None  None  None  None
53      3.688150    K3Q    E5V  None  None  None  None  None  None  None
56      3.619344    K3Q  K101R  None  None  None  None  None  None  None
...          ...    ...    ...   ...   ...   ...   ...   ...   ...   ...
51688   3.577787  M233K  D234G  None  None  None  None  None  None  None
51691   3.744741  D234G  L236P  None  None  None  None  None  None  None
51694   3.865135  D234V  Y237H  None  None  None  None  None  None  None
51696   3.693903  D234G  E235V  None  None  None  None  None  None  None
51699   3.862731  E235G  L236P  None  None  None  None  None  None  None

        m10   m11   m12   m13   m14   m15
13     None  None  None  None  None  None
41     None  None  None  None  None  None
45     None  None  None  None  None  None
53     None  None  None  None  None  None
56     None  None  None  None  None  None
...     ...   ...   ...   ...   ...   ...
51688  None  None  None  None  None  None
51691  None  None  None  None  None  None
51694  None  None  None  None  None  None
51696  None  None  None  None  None  None
51699  None  None  None  None  None  None

[12777 rows x 16 columns]

In [44]:
# copy df
df_2_mutations_filtered = df_2_mutations.copy()

# create a new df for each mut in possible_mut_1x_mut
df_2_mutations_filtered_by = {}
possible_mut_2x_mut_with = {}

for mut in possible_mut_1x_mut:
    # copy df
    df_2_mutations_filtered = df_2_mutations.copy()
    # df remaining rows with mut
    df_2_mutations_filtered = df_2_mutations_filtered[df_2_mutations_filtered.apply(lambda row: mut in row.values, axis=1)]
    # assign to mut
    df_2_mutations_filtered_by[mut] = df_2_mutations_filtered

    # create list with possible mutations of the new df
    possible_mut_2x_mut = list(set(df_2_mutations_filtered.values.flatten()))
    # remove duplicates
    possible_mut_2x_mut = list(set(possible_mut_2x_mut))
    # remove mut if it exists in the list (if, because some mut are not available in df_2_mutations
    if mut in possible_mut_2x_mut:
        possible_mut_2x_mut.remove(mut)
    # remove None
    possible_mut_2x_mut = [value for value in possible_mut_2x_mut if value is not None]
    # remove fscore from list
    possible_mut_2x_mut = [value for value in possible_mut_2x_mut if not isinstance(value, (int, float))]
    # assign to mut
    possible_mut_2x_mut_with[mut] = possible_mut_2x_mut

# print df for each mut in possible_mut_1x_mut
for mut, df_2_mutations_filtered in df_2_mutations_filtered_by.items():
    # print df
    print(f"Filtered df for mutation '{mut}':")
    print(df_2_mutations_filtered)
    # print list
    print(possible_mut_2x_mut_with[mut])
    print()

Filtered df for mutation 'T118K':
       DMS_score     m1     m2    m3    m4    m5    m6    m7    m8    m9  \
43296   3.623038  T118K  V150A  None  None  None  None  None  None  None
43297   3.570728  T118K  E172K  None  None  None  None  None  None  None
43298   3.735918  T118K  D155G  None  None  None  None  None  None  None

        m10   m11   m12   m13   m14   m15
43296  None  None  None  None  None  None
43297  None  None  None  None  None  None
43298  None  None  None  None  None  None
['D155G', 'V150A', 'E172K']

Filtered df for mutation 'N170T':
       DMS_score    m1     m2    m3    m4    m5    m6    m7    m8    m9   m10  \
28765   3.567851  T59S  N170T  None  None  None  None  None  None  None  None

        m11   m12   m13   m14   m15
28765  None  None  None  None  None
['T59S']

Filtered df for mutation 'D133A':
       DMS_score     m1     m2    m3    m4    m5    m6    m7    m8    m9  \
13      3.716293    K3R  D133A  None  None  None  None  None  None  None
45604   1.301030  D133A  Q183R  None  None  None  None  None  None  None
45605   3.602574  D133A  N159S  None  None  None  None  None  None  None
45656   3.693564  D133A  K209N  None  None  None  None  None  None  None
45657   3.589324  D133A  N149S  None  None  None  None  None  None  None

        m10   m11   m12   m13   m14   m15
13     None  None  None  None  None  None
45604  None  None  None  None  None  None
45605  None  None  None  None  None  None
45656  None  None  None  None  None  None
45657  None  None  None  None  None  None
['N149S', 'N159S', 'Q183R', 'K209N', 'K3R']

Filtered df for mutation 'P211A':
       DMS_score     m1     m2    m3    m4    m5    m6    m7    m8    m9  \
1459    3.561134    E5G  P211A  None  None  None  None  None  None  None
20133   3.717130   A37T  P211A  None  None  None  None  None  None  None
23035   3.643039   T43A  P211A  None  None  None  None  None  None  None
51399   3.471252  P211A  T225A  None  None  None  None  None  None  None

        m10   m11   m12   m13   m14   m15
1459   None  None  None  None  None  None
20133  None  None  None  None  None  None
23035  None  None  None  None  None  None
51399  None  None  None  None  None  None
['T225A', 'T43A', 'A37T', 'E5G']

Filtered df for mutation 'H81P':
       DMS_score    m1     m2    m3    m4    m5    m6    m7    m8    m9   m10  \
35444   3.138284  H81P  I229N  None  None  None  None  None  None  None  None

        m11   m12   m13   m14   m15
35444  None  None  None  None  None
['I229N']

Filtered df for mutation 'S86A':
       DMS_score    m1     m2    m3    m4    m5    m6    m7    m8    m9   m10  \
13954   3.498689  G24S   S86A  None  None  None  None  None  None  None  None
36819   3.641543  S86A  S202G  None  None  None  None  None  None  None  None
36821   1.371763  S86A   Q94R  None  None  None  None  None  None  None  None
36823   3.734323  S86A  P187T  None  None  None  None  None  None  None  None
36824   3.871102  S86A  N105T  None  None  None  None  None  None  None  None
36829   3.571282  S86A  K107E  None  None  None  None  None  None  None  None
36830   3.328508  S86A  I152L  None  None  None  None  None  None  None  None
36832   3.743785  S86A  I128T  None  None  None  None  None  None  None  None
36836   3.699199  S86A  S202R  None  None  None  None  None  None  None  None
36838   3.108504  S86A  V224E  None  None  None  None  None  None  None  None

        m11   m12   m13   m14   m15
13954  None  None  None  None  None
36819  None  None  None  None  None
36821  None  None  None  None  None
36823  None  None  None  None  None
36824  None  None  None  None  None
36829  None  None  None  None  None
36830  None  None  None  None  None
36832  None  None  None  None  None
36836  None  None  None  None  None
36838  None  None  None  None  None
['P187T', 'K107E', 'S202R', 'G24S', 'N105T', 'I128T', 'I152L', 'S202G', 'Q94R', 'V224E']

Filtered df for mutation 'K107G':
       DMS_score    m1     m2    m3    m4    m5    m6    m7    m8    m9   m10  \
27320   3.368358  K52R  K107G  None  None  None  None  None  None  None  None

        m11   m12   m13   m14   m15
27320  None  None  None  None  None
['K52R']

Filtered df for mutation 'D82V':
       DMS_score    m1     m2    m3    m4    m5    m6    m7    m8    m9   m10  \
35709   1.475694  D82V  K156E  None  None  None  None  None  None  None  None
35713   1.444225  D82V  H199R  None  None  None  None  None  None  None  None
35717   1.727627  D82V   M88I  None  None  None  None  None  None  None  None
35719   1.360807  D82V  H231R  None  None  None  None  None  None  None  None
35735   1.301032  D82V  N149I  None  None  None  None  None  None  None  None
35736   1.648909  D82V  N121Y  None  None  None  None  None  None  None  None
35830   1.502044  D82V  A110D  None  None  None  None  None  None  None  None
35833   1.301031  D82V  D216E  None  None  None  None  None  None  None  None

        m11   m12   m13   m14   m15
35709  None  None  None  None  None
35713  None  None  None  None  None
35717  None  None  None  None  None
35719  None  None  None  None  None
35735  None  None  None  None  None
35736  None  None  None  None  None
35830  None  None  None  None  None
35833  None  None  None  None  None
['K156E', 'M88I', 'H199R', 'A110D', 'D216E', 'N149I', 'H231R', 'N121Y']

Filtered df for mutation 'D76E':
       DMS_score    m1     m2    m3    m4    m5    m6    m7    m8    m9   m10  \
18327   3.731834  E32G   D76E  None  None  None  None  None  None  None  None
32517   3.742932  F71L   D76E  None  None  None  None  None  None  None  None
33656   3.627236  D76E  N198D  None  None  None  None  None  None  None  None
33657   3.635927  D76E  N164S  None  None  None  None  None  None  None  None
33658   3.625445  D76E  N164D  None  None  None  None  None  None  None  None
33660   3.718670  D76E  N105S  None  None  None  None  None  None  None  None
33661   3.696446  D76E  M153V  None  None  None  None  None  None  None  None
33664   3.744655  D76E   H81L  None  None  None  None  None  None  None  None

        m11   m12   m13   m14   m15
18327  None  None  None  None  None
32517  None  None  None  None  None
33656  None  None  None  None  None
33657  None  None  None  None  None
33658  None  None  None  None  None
33660  None  None  None  None  None
33661  None  None  None  None  None
33664  None  None  None  None  None
['F71L', 'N198D', 'E32G', 'H81L', 'M153V', 'N164D', 'N105S', 'N164S']

Filtered df for mutation 'H148Q':
       DMS_score     m1     m2    m3    m4    m5    m6    m7    m8    m9  \
32720   3.608985   S72G  H148Q  None  None  None  None  None  None  None
42523   3.631628  F114L  H148Q  None  None  None  None  None  None  None
47671   1.402609  H148Q  L220P  None  None  None  None  None  None  None

        m10   m11   m12   m13   m14   m15
32720  None  None  None  None  None  None
42523  None  None  None  None  None  None
47671  None  None  None  None  None  None
['L220P', 'F114L', 'S72G']

Filtered df for mutation 'L125R':
       DMS_score    m1     m2    m3    m4    m5    m6    m7    m8    m9   m10  \
23002    1.30103  T43A  L125R  None  None  None  None  None  None  None  None

        m11   m12   m13   m14   m15
23002  None  None  None  None  None
['T43A']

Filtered df for mutation 'E6G':
      DMS_score   m1     m2    m3    m4    m5    m6    m7    m8    m9   m10  \
88     3.705394  K3R    E6G  None  None  None  None  None  None  None  None
2333   3.790718  E5G    E6G  None  None  None  None  None  None  None  None
2407   3.754837  E6G  I229T  None  None  None  None  None  None  None  None
2411   3.652307  E6G  I167V  None  None  None  None  None  None  None  None
2412   3.546184  E6G  I167N  None  None  None  None  None  None  None  None
...         ...  ...    ...   ...   ...   ...   ...   ...   ...   ...   ...
3018   3.579803  E6G  V224A  None  None  None  None  None  None  None  None
3050   3.771881  E6G   V29L  None  None  None  None  None  None  None  None
3055   3.796690  E6G   T38S  None  None  None  None  None  None  None  None
3087   3.648888  E6G  V112A  None  None  None  None  None  None  None  None
3088   3.175897  E6G   T63S  None  None  None  None  None  None  None  None

       m11   m12   m13   m14   m15
88    None  None  None  None  None
2333  None  None  None  None  None
2407  None  None  None  None  None
2411  None  None  None  None  None
2412  None  None  None  None  None
...    ...   ...   ...   ...   ...
3018  None  None  None  None  None
3050  None  None  None  None  None
3055  None  None  None  None  None
3087  None  None  None  None  None
3088  None  None  None  None  None

[81 rows x 16 columns]
['M78T', 'Y39N', 'I167N', 'F27S', 'T38S', 'I167V', 'S28I', 'T203A', 'N149Y', 'M218V', 'D190G', 'V224A', 'G232S', 'N164D', 'N159S', 'K166E', 'P211H', 'F165S', 'I136T', 'F165V', 'F8L', 'D117N', 'D103G', 'N212H', 'T230A', 'H77P', 'D36G', 'H139R', 'S28N', 'E95G', 'N149S', 'R73C', 'N159Y', 'L141Q', 'I229T', 'I123T', 'F223S', 'Y200F', 'E5G', 'K3R', 'D234G', 'I123V', 'D19N', 'T63S', 'P89L', 'L178H', 'Y151N', 'S72C', 'V112A', 'G138R', 'N159I', 'I136S', 'N149D', 'Y106C', 'T108A', 'Y145N', 'K113E', 'M153L', 'D133G', 'L18P', 'S147C', 'K140E', 'V29L', 'N164I', 'C70S', 'N146I', 'F46L', 'S30T', 'K158R', 'E34V', 'L53P', 'K113R', 'H139L', 'N159D', 'Q157R', 'I14T', 'H81N', 'N198D', 'Y39S', 'H169L', 'F223L']

Filtered df for mutation 'V61M':
       DMS_score    m1     m2    m3    m4    m5    m6    m7    m8    m9   m10  \
16538   3.124656  S28G   V61M  None  None  None  None  None  None  None  None
24990   3.328359  I47V   V61M  None  None  None  None  None  None  None  None
29385   3.137350  V61M  D117G  None  None  None  None  None  None  None  None
29496   2.331257  V61M  N149S  None  None  None  None  None  None  None  None
29504   1.304147  V61M  I136N  None  None  None  None  None  None  None  None

        m11   m12   m13   m14   m15
16538  None  None  None  None  None
24990  None  None  None  None  None
29385  None  None  None  None  None
29496  None  None  None  None  None
29504  None  None  None  None  None
['D117G', 'S28G', 'N149S', 'I136N', 'I47V']

Filtered df for mutation 'S205F':
       DMS_score     m1     m2    m3    m4    m5    m6    m7    m8    m9  \
51108   1.301032  D197V  S205F  None  None  None  None  None  None  None

        m10   m11   m12   m13   m14   m15
51108  None  None  None  None  None  None
['D197V']

Filtered df for mutation 'T59A':
       DMS_score    m1     m2    m3    m4    m5    m6    m7    m8    m9   m10  \
6903    3.541450  V11A   T59A  None  None  None  None  None  None  None  None
9136    3.533693  L15Q   T59A  None  None  None  None  None  None  None  None
20870   3.728517  Y39F   T59A  None  None  None  None  None  None  None  None
25863   3.049298  C48S   T59A  None  None  None  None  None  None  None  None
27084   3.742280  K52E   T59A  None  None  None  None  None  None  None  None
...          ...   ...    ...   ...   ...   ...   ...   ...   ...   ...   ...
28953   3.598174  T59A   H77R  None  None  None  None  None  None  None  None
28955   3.522033  T59A  I123V  None  None  None  None  None  None  None  None
28957   3.692612  T59A  I136V  None  None  None  None  None  None  None  None
28960   3.631174  T59A  I128T  None  None  None  None  None  None  None  None
28962   3.643992  T59A  I171T  None  None  None  None  None  None  None  None

        m11   m12   m13   m14   m15
6903   None  None  None  None  None
9136   None  None  None  None  None
20870  None  None  None  None  None
25863  None  None  None  None  None
27084  None  None  None  None  None
...     ...   ...   ...   ...   ...
28953  None  None  None  None  None
28955  None  None  None  None  None
28957  None  None  None  None  None
28960  None  None  None  None  None
28962  None  None  None  None  None

[42 rows x 16 columns]
['Y200H', 'I136V', 'H199R', 'K52E', 'N212S', 'V193E', 'N135S', 'K156E', 'L236Q', 'L15Q', 'K52M', 'N121S', 'D197G', 'N198S', 'E142G', 'M233K', 'C48S', 'Y39F', 'I123V', 'L178P', 'S175G', 'N170I', 'M233T', 'L195P', 'K162Q', 'Q157L', 'V11A', 'T108A', 'F100Y', 'K214R', 'Q177L', 'I128T', 'D234Y', 'N149I', 'F99L', 'K113R', 'Q157R', 'H77R', 'I171T', 'T62S', 'K214E', 'T186S']

Filtered df for mutation 'K156R':
       DMS_score     m1     m2    m3    m4    m5    m6    m7    m8    m9  \
320     3.716797    K3R  K156R  None  None  None  None  None  None  None
2907    3.573225    E6V  K156R  None  None  None  None  None  None  None
4252    3.953244    F8L  K156R  None  None  None  None  None  None  None
6711    3.552528   V11G  K156R  None  None  None  None  None  None  None
11209   3.610729   D19G  K156R  None  None  None  None  None  None  None
...          ...    ...    ...   ...   ...   ...   ...   ...   ...   ...
48579   3.510415  K156R  I161T  None  None  None  None  None  None  None
48584   3.437945  K156R  F165S  None  None  None  None  None  None  None
48587   3.788760  K156R  D234V  None  None  None  None  None  None  None
48594   3.654615  K156R  D180G  None  None  None  None  None  None  None
48648   3.673494  K156R  K162E  None  None  None  None  None  None  None

        m10   m11   m12   m13   m14   m15
320    None  None  None  None  None  None
2907   None  None  None  None  None  None
4252   None  None  None  None  None  None
6711   None  None  None  None  None  None
11209  None  None  None  None  None  None
...     ...   ...   ...   ...   ...   ...
48579  None  None  None  None  None  None
48584  None  None  None  None  None  None
48587  None  None  None  None  None  None
48594  None  None  None  None  None  None
48648  None  None  None  None  None  None

[99 rows x 16 columns]
['K26E', 'K26M', 'K101R', 'Y200H', 'M233V', 'Y151C', 'F130Y', 'V163L', 'K162E', 'V68L', 'F71S', 'S30C', 'I167V', 'I161V', 'N149Y', 'V163A', 'V224A', 'F27L', 'K166E', 'D117G', 'F165S', 'T62A', 'I152V', 'I161T', 'L64P', 'F8L', 'I136T', 'D117N', 'D103G', 'K126R', 'N212H', 'D19G', 'E32G', 'N23S', 'N198S', 'E95G', 'E115K', 'I123T', 'E142G', 'E6V', 'T118A', 'I188V', 'K3R', 'E111K', 'M233K', 'D234V', 'C48S', 'T43A', 'E90G', 'E124G', 'S30F', 'S175G', 'T118I', 'Q184R', 'N146S', 'N170I', 'V112A', 'I128V', 'K131Q', 'M233T', 'A226T', 'N170H', 'M88T', 'H25R', 'G31D', 'N144S', 'I47F', 'K140R', 'S147G', 'M218T', 'F130L', 'A87T', 'I152F', 'N144Y', 'D133G', 'I128N', 'T230N', 'C70S', 'V11G', 'F46L', 'K45E', 'K158R', 'D180G', 'T59S', 'F99L', 'D21G', 'K113R', 'D129N', 'D173G', 'N159D', 'S28G', 'I167A', 'I167S', 'M153K', 'V93A', 'L221Q', 'Y182F', 'K214E', 'K52R']

Filtered df for mutation 'I167N':
       DMS_score     m1     m2    m3    m4    m5    m6    m7    m8    m9  \
2412    3.546184    E6G  I167N  None  None  None  None  None  None  None
20199   3.455494   T38A  I167N  None  None  None  None  None  None  None
30850   1.301030   Y66C  I167N  None  None  None  None  None  None  None
33733   3.193503   D76G  I167N  None  None  None  None  None  None  None
34585   3.658335   K79R  I167N  None  None  None  None  None  None  None
...          ...    ...    ...   ...   ...   ...   ...   ...   ...   ...
48784   3.297763  K158E  I167N  None  None  None  None  None  None  None
49512   3.470076  N164Y  I167N  None  None  None  None  None  None  None
49807   3.259355  I167N  S208G  None  None  None  None  None  None  None
49817   3.535003  I167N  I229V  None  None  None  None  None  None  None
49826   3.528386  I167N  M233K  None  None  None  None  None  None  None

        m10   m11   m12   m13   m14   m15
2412   None  None  None  None  None  None
20199  None  None  None  None  None  None
30850  None  None  None  None  None  None
33733  None  None  None  None  None  None
34585  None  None  None  None  None  None
...     ...   ...   ...   ...   ...   ...
48784  None  None  None  None  None  None
49512  None  None  None  None  None  None
49807  None  None  None  None  None  None
49817  None  None  None  None  None  None
49826  None  None  None  None  None  None

[17 rows x 16 columns]
['E6G', 'D82Y', 'K158E', 'N164Y', 'Y66C', 'K101E', 'K79R', 'Q157R', 'N105S', 'S208G', 'M233K', 'D76G', 'T38A', 'M153V', 'V150A', 'I229V', 'D133G']

Filtered df for mutation 'D102G':
       DMS_score     m1     m2    m3    m4    m5    m6    m7    m8    m9  \
1675    3.750820    E5K  D102G  None  None  None  None  None  None  None
1851    3.719787    E5V  D102G  None  None  None  None  None  None  None
2319    3.918239    E5G  D102G  None  None  None  None  None  None  None
6557    3.475906   V11E  D102G  None  None  None  None  None  None  None
9478    3.201646   V16A  D102G  None  None  None  None  None  None  None
...          ...    ...    ...   ...   ...   ...   ...   ...   ...   ...
40566   3.480369  D102G  K126E  None  None  None  None  None  None  None
40567   3.533289  D102G  I188T  None  None  None  None  None  None  None
40570   3.731560  D102G  K113R  None  None  None  None  None  None  None
40574   3.601055  D102G  K107E  None  None  None  None  None  None  None
40575   3.826107  D102G  I229V  None  None  None  None  None  None  None

        m10   m11   m12   m13   m14   m15
1675   None  None  None  None  None  None
1851   None  None  None  None  None  None
2319   None  None  None  None  None  None
6557   None  None  None  None  None  None
9478   None  None  None  None  None  None
...     ...   ...   ...   ...   ...   ...
40566  None  None  None  None  None  None
40567  None  None  None  None  None  None
40570  None  None  None  None  None  None
40574  None  None  None  None  None  None
40575  None  None  None  None  None  None

[86 rows x 16 columns]
['Y182N', 'T230S', 'K107E', 'T230I', 'K162E', 'C48W', 'N135D', 'Y39C', 'K52E', 'I188T', 'N146D', 'K166E', 'G134S', 'N212S', 'T63A', 'L194Q', 'I161T', 'N135Y', 'V193E', 'M153V', 'V193G', 'F165L', 'N135S', 'E32G', 'K126E', 'K79E', 'E90V', 'N121S', 'I171F', 'N149S', 'Q157P', 'L141Q', 'K209R', 'N105D', 'Y66F', 'K79R', 'H181L', 'K52R', 'E5G', 'S208G', 'M233K', 'Q80R', 'S65L', 'C48S', 'Y145F', 'E124G', 'I229V', 'Y151F', 'L178H', 'I128V', 'R122S', 'Q184L', 'E111G', 'I47V', 'V11E', 'S202G', 'N170S', 'F130L', 'Y106C', 'Y143H', 'I123M', 'D117V', 'D133G', 'D197N', 'E5K', 'N185D', 'Q177L', 'N146I', 'K158R', 'E34V', 'E5V', 'K113R', 'K158W', 'H139L', 'S205P', 'K26T', 'N105S', 'I171T', 'K166Q', 'V16A', 'N23D', 'M218L', 'V150A', 'F223L', 'S175C', 'E34G']

Filtered df for mutation 'V68L':
       DMS_score    m1     m2    m3    m4    m5    m6    m7    m8    m9   m10  \
29767   3.494144  T62A   V68L  None  None  None  None  None  None  None  None
31456   3.531054  V68L  D234N  None  None  None  None  None  None  None  None
31457   3.393796  V68L   F83L  None  None  None  None  None  None  None  None
31459   3.414579  V68L   H81R  None  None  None  None  None  None  None  None
31462   3.591518  V68L  I128L  None  None  None  None  None  None  None  None
...          ...   ...    ...   ...   ...   ...   ...   ...   ...   ...   ...
31465   3.581470  V68L  K209R  None  None  None  None  None  None  None  None
31466   3.366307  V68L  M218I  None  None  None  None  None  None  None  None
31467   3.656595  V68L  N212I  None  None  None  None  None  None  None  None
31468   3.687561  V68L  T118S  None  None  None  None  None  None  None  None
31469   3.507747  V68L  V112A  None  None  None  None  None  None  None  None

        m11   m12   m13   m14   m15
29767  None  None  None  None  None
31456  None  None  None  None  None
31457  None  None  None  None  None
31459  None  None  None  None  None
31462  None  None  None  None  None
...     ...   ...   ...   ...   ...
31465  None  None  None  None  None
31466  None  None  None  None  None
31467  None  None  None  None  None
31468  None  None  None  None  None
31469  None  None  None  None  None

[11 rows x 16 columns]
['I128L', 'N212I', 'K156R', 'V112A', 'M218I', 'H81R', 'K209R', 'T118S', 'T62A', 'F83L', 'D234N']

Filtered df for mutation 'L7Q':
      DMS_score   m1     m2    m3    m4    m5    m6    m7    m8    m9   m10  \
3489   1.595854  L7Q   P56L  None  None  None  None  None  None  None  None

In [46]:
# df mutants with 3x mutations
# copy df
df_3_mutations = df_only_fscore_mutations.copy()

# delete mutants with < 3 mutations
df_3_mutations = df_3_mutations.dropna(subset=['m3'])

# remain rows with empty values in m4
df_3_mutations = df_3_mutations[df_3_mutations['m4'].isna()]

print(df_3_mutations)

       DMS_score     m1     m2     m3    m4    m5    m6    m7    m8    m9  \
3       3.404237    K3Q  Y143N  V193A  None  None  None  None  None  None
5       3.851893    K3R   A87T  D173G  None  None  None  None  None  None
10      1.301030    K3R  D102V  H217L  None  None  None  None  None  None
11      3.875060    K3R  D117G  V163A  None  None  None  None  None  None
14      3.722024    K3R  D133G  L195Q  None  None  None  None  None  None
...          ...    ...    ...    ...   ...   ...   ...   ...   ...   ...
51560   3.374411  F223C  V224A  M233T  None  None  None  None  None  None
51572   3.675968  F223S  E235K  Y237C  None  None  None  None  None  None
51574   3.628175  F223S  M233K  L236Q  None  None  None  None  None  None
51577   3.223593  F223S  V224A  E235V  None  None  None  None  None  None
51629   3.741126  I229V  G232S  L236P  None  None  None  None  None  None

        m10   m11   m12   m13   m14   m15
3      None  None  None  None  None  None
5      None  None  None  None  None  None
10     None  None  None  None  None  None
11     None  None  None  None  None  None
14     None  None  None  None  None  None
...     ...   ...   ...   ...   ...   ...
51560  None  None  None  None  None  None
51572  None  None  None  None  None  None
51574  None  None  None  None  None  None
51577  None  None  None  None  None  None
51629  None  None  None  None  None  None

[12336 rows x 16 columns]

In [ ]:
# filter df_3_mutations with possible_mut_1x_mut
# copy df
df_3_mutations_filtered = df_3_mutations.copy()

# create a new df for each mut in possible_mut_1x_mut
df_3_mutations_filtered_by = {}
# create a new list for each mut in possible_mut_1x_mut
possible_mut_3x_mut_with = {}

for mut in possible_mut_1x_mut:
    # copy df
    df_3_mutations_filtered = df_3_mutations.copy()
    # df remaining rows with mut
    df_3_mutations_filtered = df_3_mutations_filtered[df_3_mutations_filtered.apply(lambda row: mut in row.values, axis=1)]
    # assign to mut
    df_3_mutations_filtered_by[mut] = df_3_mutations_filtered

# print df for each mut in possible_mut_1x_mut
for mut, df_2_mutations_filtered in df_2_mutations_filtered_by.items():
    # print df
    print(f"Filtered df for mutation '{mut}':")
    print(df_2_mutations_filtered)
    # print list
    print(possible_mut_2x_mut_with[mut])
    print()